name: Deploy Auth Backend to GCP

on:
  push:
    branches:
    - main

env:
  PROJECT_ID: your-gcp-project-id
  GCP_REGION: us-central1
  IMAGE_NAME: auth-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 'Authenticate to Google Cloud'
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Set up Docker'
      uses: docker/setup-docker@v2

    - name: 'Configure Docker for GCP Artifact Registry'
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }} .
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.IMAGE_NAME }} # El nombre del servicio en Cloud Run
        region: ${{ env.GCP_REGION }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}
        env_vars: |
          # Agrega aquí las variables de entorno específicas para tu servicio de autenticación
          # Ejemplo: JWT_SECRET=${{ secrets.JWT_SECRET }}
